'''
t = (1,2,3,4)
for i in t:
    print(i)
print(t.count(1))
'''
'''

# bytes data type

l = [1,2,3,4]
b = bytes(l)
for i in b:
    print(i)
print(type(b))

'''

# bytearray data type

''''
l = [10,20,30,40,50]
b = bytearray(l)
for i in b:
    print(i)
    b[0] = 100
for j in b:
    print(j)


#  set data type

s = {1,2,3,4,5,5}
print(s)

s.add(6)
for i in s:
    print(i)
s.remove(5)
for k in s:
    print(k)

    '''

'''
f = {10,20,40,50}
print(f)
for i in f:
    print(i)
    
'''

'''
# dict data type


dic = {}
dic[1] = 'Java'
dic[2] = 'Python'

for i in dic:
    print(dic)
'''

